### PR TITLE
Fix wrong component name separator

### PR DESCRIPTION
**Pull request by simplect**
Fixed a wrong component name. It broke all components after Separator.

### CODE REVIEW

**Comment by LukasRychtecky** [comment]
If this could be merged, it would be fine :)

**Comment by simplect** [comment]
You can use [simplect/antizer "3.26.12-1"] for now. I am planning on creating a new project to continue maintenance. If I do so, it will be here: https://github.com/simplect/cljs-ant

**Comment by aceful** [comment]
@christoph-frick Are you still planning to maintain this fork?

**Comment by christoph-frick** [comment]
I am sorry, but GH failed to inform me about this pull request. Thanks for the PR

**Pull request merged**
